version: "3"
# containers are refered to as services
services:
  dummycontainer:
    build:
      context: .
      args: 
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: npm run dev
