version: "3"
# containers are refered to as services
services:
  dummycontainer:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  mongo:
     image: mongo 
     environment: 
        - MONGO_INITDB_ROOT_USERNAME=lad
        - MONGO_INITDB_ROOT_PASSWORD=sikk
     volumes:
        - mongo-db:/data/db

volumes:
  mongo-db: